{% set name = "imbalanced-ensemble" %}
{% set version = "0.2.2" %}
{% set commit_id = "30940ad5c351a9c966fdcff82c534e8b96a33753" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/imbalanced-ensemble-{{ version }}.tar.gz
    sha256: 0bc0dddf9a6a574fd087fa6d80e2545b59a71cfd20b56c4adadfb8b7e8370667
  # upstream forgot to include requirements.txt used to source dependencies
  # in setup.py. The file is obtained at a commit id relative to the version
  # 0.2.2 because there are no release tags after 0.2.0.
  # See: https://github.com/ZhiningLiu1998/imbalanced-ensemble/blob/62dc2c7fa0c66ed2a6ee4c082a7f46f84b4cfeca/requirements.txt
  - url: https://raw.githubusercontent.com/ZhiningLiu1998/{{ name }}/{{ commit_id }}/requirements.txt
    sha256: b3f82c41ba1756b63b7fb9dbe1fbaf755658a48c84dfac04fea1e55c55f90783

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  skip: True  # [py<39]

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools
  run:
    - python
    - numpy >=1.16.0
    - scipy >=1.9.1
    - pandas >=2.1.1
    - joblib >=0.11
    - scikit-learn >=1.5.0
    - matplotlib-base >=3.3.2
    - seaborn >=0.13.2
    - tqdm >=4.50.2

test:
  source_files:
    - ./imbens/utils/tests
  imports:
    - imbens
  commands:
    - pip check
    - pytest -v .
  requires:
    - pip
    - pytest

about:
  home: https://github.com/ZhiningLiu1998/imbalanced-ensemble
  summary: Toolbox for ensemble learning on class-imbalanced dataset.
  description: |
    IMBENS (imported as imbens) is a Python library for quick implementation, modification, evaluation, and 
    visualization of ensemble learning from class-imbalanced data.
  license: MIT
  license_file: LICENSE
  license_family: MIT
  dev_url: https://github.com/ZhiningLiu1998/imbalanced-ensemble
  doc_url: https://imbalanced-ensemble.readthedocs.io/

extra:
  recipe-maintainers:
    - psteyer
